name: gamytask_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_gif: 0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/loading.gif
  fonts:
    - family: arcade
      fonts:
        - asset: assets\font\DePixelBreit.ttf

  uses-material-design: true
