// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVHmuUoqt_Hxhqhl2TlMqSJqAGriRS3SA',
    appId: '1:307326463157:web:6411d693ca021e53a2a2fc',
    messagingSenderId: '307326463157',
    projectId: 'gamy-bd345',
    authDomain: 'gamy-bd345.firebaseapp.com',
    databaseURL: 'https://gamy-bd345-default-rtdb.firebaseio.com',
    storageBucket: 'gamy-bd345.firebasestorage.app',
    measurementId: 'G-CB6D5VLLX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnCgmTZT5rHZ8GCyhyH2urSxKQ3QRwLQ4',
    appId: '1:307326463157:android:44a1ede97a93d9b9a2a2fc',
    messagingSenderId: '307326463157',
    projectId: 'gamy-bd345',
    databaseURL: 'https://gamy-bd345-default-rtdb.firebaseio.com',
    storageBucket: 'gamy-bd345.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG5ze6ZjhAqa1jlcSweuKqr2clrNSj_8o',
    appId: '1:307326463157:ios:f4cbf09c0a53e1e5a2a2fc',
    messagingSenderId: '307326463157',
    projectId: 'gamy-bd345',
    databaseURL: 'https://gamy-bd345-default-rtdb.firebaseio.com',
    storageBucket: 'gamy-bd345.firebasestorage.app',
    iosBundleId: 'com.example.gamytaskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG5ze6ZjhAqa1jlcSweuKqr2clrNSj_8o',
    appId: '1:307326463157:ios:f4cbf09c0a53e1e5a2a2fc',
    messagingSenderId: '307326463157',
    projectId: 'gamy-bd345',
    databaseURL: 'https://gamy-bd345-default-rtdb.firebaseio.com',
    storageBucket: 'gamy-bd345.firebasestorage.app',
    iosBundleId: 'com.example.gamytaskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVHmuUoqt_Hxhqhl2TlMqSJqAGriRS3SA',
    appId: '1:307326463157:web:cc9a0cfb616c48b0a2a2fc',
    messagingSenderId: '307326463157',
    projectId: 'gamy-bd345',
    authDomain: 'gamy-bd345.firebaseapp.com',
    databaseURL: 'https://gamy-bd345-default-rtdb.firebaseio.com',
    storageBucket: 'gamy-bd345.firebasestorage.app',
    measurementId: 'G-2K0GVW8EPF',
  );
}
